name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.4.3
  - conda=23.1.0
  - cudatoolkit=11.8.0
  - cudnn=8.4.1.50
  - cupy=11.6.0
  - dask=2023.1.1
  - dask-cuda=23.2.1
  - distributed=2023.1.1
  - graphviz=7.1.0
  - jupyter=1.0.0
  - keras=2.11.0
  - mamba=1.3.1
  - napari=0.4.17
  - netcdf4=1.6.3
  - numba=0.56.4
  - numpy=1.23.5
  - rioxarray=0.13.4
  - scikit-image=0.19.3
  - scipy=1.10.1
  - tensorflow=2.11.0
  - tensorflow-gpu=2.11.0

